-- ============================================================
-- Migration 007: Artifacts
--
-- Rich, shareable HTML documents generated by agents.
-- Research summaries, monthly reports, member plans, ROI cards.
--
-- Run in Supabase SQL Editor.
-- ============================================================

CREATE TABLE IF NOT EXISTS artifacts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  gym_id UUID NOT NULL REFERENCES gyms(id),
  artifact_type TEXT NOT NULL,       -- 'research_summary' | 'monthly_report' | 'member_plan' | 'roi_card'
  title TEXT NOT NULL,
  data JSONB NOT NULL DEFAULT '{}',  -- structured data for rendering
  html TEXT,                         -- rendered HTML (cached)
  task_id UUID,                      -- optional link to source task
  created_by TEXT NOT NULL,          -- 'gm' | 'retention' | 'system' | 'owner'
  share_token TEXT,                  -- for public sharing via URL (nullable = private)
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_artifacts_gym ON artifacts (gym_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_artifacts_share ON artifacts (share_token) WHERE share_token IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_artifacts_task ON artifacts (task_id) WHERE task_id IS NOT NULL;
